"""
Data-cleansing showcase - detailed, audited, on the REAL raw data.

Online Retail II arrives genuinely messy. This script makes the cleaning visible:
it pulls real example rows for every issue type, then runs the exact same
CLEANING_STEPS used by the production pipeline (imported from clean.py - no drift),
recording rows in/out at each step.

Outputs:
  docs/cleaning_showcase.md             (narrative + example tables + audit)
  reports/tables/clean_audit.csv        (step-by-step row counts)
  reports/tables/dirty_examples_*.csv   (real dirty rows, per issue)

Run:  python -m src.data.cleaning_showcase
"""
from __future__ import annotations
import logging
from pathlib import Path
import pandas as pd

from src.data.clean import RAW_FILE, COLUMN_RENAME, CLEANING_STEPS, PRODUCT_CODE_PATTERN

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(message)s", datefmt="%H:%M:%S")
log = logging.getLogger("cleaning_showcase")

ROOT = Path(__file__).resolve().parents[2]
PROC = ROOT / "data" / "processed"
TAB = ROOT / "reports" / "tables"
DOCS = ROOT / "docs"
RAW_CACHE = PROC / "raw_concat.parquet"
TAB.mkdir(parents=True, exist_ok=True)


def load_raw_fast() -> pd.DataFrame:
    """Load + concat both sheets (cached to parquet). Uses the fast calamine engine."""
    if RAW_CACHE.exists():
        log.info("Reading cached raw concat parquet ...")
        return pd.read_parquet(RAW_CACHE)
    log.info("Reading workbook via calamine (fast) ...")
    sheets = pd.read_excel(RAW_FILE, sheet_name=None, engine="calamine")
    df = pd.concat(sheets.values(), ignore_index=True).rename(columns=COLUMN_RENAME)
    for c in df.columns:
        if df[c].dtype == object:
            df[c] = df[c].astype("string")
    df.to_parquet(RAW_CACHE, index=False)
    log.info("Loaded %s raw rows from %d sheets.", f"{len(df):,}", len(sheets))
    return df


def md_table(df: pd.DataFrame) -> str:
    return "```\n" + df.to_string(index=False) + "\n```"


def collect_examples(raw: pd.DataFrame) -> dict:
    """Pull a few REAL dirty rows for each issue type, straight from the raw data."""
    cols = ["invoice", "stock_code", "description", "quantity", "price", "customer_id"]
    inv = raw["invoice"].astype(str)
    sc = raw["stock_code"].astype(str)
    ex = {}
    dup_mask = raw.duplicated(keep=False)
    if dup_mask.any():
        key = raw[dup_mask].iloc[0][cols]
        ex["duplicates"] = raw[(raw[cols] == key).all(axis=1)][cols].head(3)
    ex["cancellations"] = raw[inv.str.upper().str.startswith("C")][cols].head(4)
    ex["missing_customer_id"] = raw[raw["customer_id"].isna()][cols].head(4)
    ex["nonpositive_qty_price"] = raw[(raw["quantity"] <= 0) | (raw["price"] <= 0)][cols].head(4)
    ex["service_codes"] = raw[~sc.str.match(PRODUCT_CODE_PATTERN)][cols].drop_duplicates("stock_code").head(6)
    ex["missing_description"] = raw[raw["description"].isna()][cols].head(4)
    return ex


def main():
    raw = load_raw_fast()
    n_raw = len(raw)

    miss = (raw.isna().mean() * 100).round(2).rename("pct_missing").to_frame()
    miss["n_missing"] = raw.isna().sum().values

    examples = collect_examples(raw)
    for name, frame in examples.items():
        frame.to_csv(TAB / f"dirty_examples_{name}.csv", index=False)

    df = raw.copy()
    audit = []
    for label, step in CLEANING_STEPS:
        before = len(df)
        df = step(df)
        after = len(df)
        audit.append({"step": label, "rows_in": before, "rows_out": after, "removed": before - after})
    audit_df = pd.DataFrame(audit)
    audit_df.to_csv(TAB / "clean_audit.csv", index=False)
    n_clean = len(df)

    issue_titles = {
        "duplicates": "Exact duplicate rows (a known dataset artefact)",
        "cancellations": "Cancellations / returns (invoice prefixed with 'C', negative qty)",
        "missing_customer_id": "Missing Customer ID (guest / unidentified baskets)",
        "nonpositive_qty_price": "Non-positive quantity or price (adjustments, freebies, write-offs)",
        "service_codes": "Non-product service / admin codes (POST, DOT, fees, ADJUST)",
        "missing_description": "Missing product description",
    }
    parts = [
        "# Data-Cleansing Showcase - the real mess, cleaned step by step\n",
        "Generated by `src/data/cleaning_showcase.py`, which reuses the **exact** "
        "`CLEANING_STEPS` from the production pipeline (`src/data/clean.py`) - so this "
        "narrative and the live code can never drift.\n",
        f"**Raw input:** `online_retail_II.xlsx` (2 sheets concatenated) = "
        f"**{n_raw:,} rows x {raw.shape[1]} columns**, Dec 2009 - Dec 2011.\n",
        "> The raw data is *not* clean - below are real rows pulled straight from it.\n",
        "---\n\n## 1. Missing values (raw)\n",
        md_table(miss.reset_index().rename(columns={"index": "column"})),
        "\n\n## 2. Real dirty rows, by issue type\n",
    ]
    for key, title in issue_titles.items():
        if key in examples and len(examples[key]):
            parts.append(f"\n**{title}** - e.g.:\n")
            parts.append(md_table(examples[key]))
            parts.append("\n")
    parts += [
        "\n---\n\n## 3. Cleaning, step by step (production logic)\n",
        "Each row below is one `CLEANING_STEPS` function, applied in order:\n",
        md_table(audit_df),
        f"\n\n**Result: {n_raw:,} -> {n_clean:,} rows ({100*n_clean/n_raw:.1f}% retained).** "
        "Service/admin lines are flagged (not deleted) so total revenue stays correct while "
        "product-level SKU and basket analysis use genuine products only.\n",
    ]
    (DOCS / "cleaning_showcase.md").write_text("".join(parts), encoding="utf-8")

    print("\n=== STEP-BY-STEP AUDIT ===")
    print(audit_df.to_string(index=False))
    print(f"\nRaw {n_raw:,} -> clean {n_clean:,} ({100*n_clean/n_raw:.1f}% retained)")
    print("Examples + audit -> reports/tables/ | narrative -> docs/cleaning_showcase.md")


if __name__ == "__main__":
    main()
